"""Adapters must be cancellation-cooperative; no blocking work in async ports."""
from typing import Protocol


class Clock(Protocol):
    def monotonic(self) -> float: ...
    def utcnow(self) -> str: ...


class Model(Protocol):
    async def choose_action(self, context: dict, allowed_tools: tuple) -> dict: ...
    async def produce_result(self, context: dict) -> dict: ...


class EvidenceTools(Protocol):
    async def get_change_event(self, event_id: str) -> dict: ...
    async def get_rbac_object(self, kind: str, namespace: str, name: str, version: str) -> dict: ...
    async def get_subject_bindings(self, subject_id: str) -> dict: ...
    async def get_approval_record(self, change_id: str) -> dict: ...


class Repository(Protocol):
    def get_by_idempotency_key(self, key: str) -> dict | None: ...
    def create_investigation(self, key: str, metadata: dict) -> bool: ...
    def append_audit_event(self, key: str, event: dict) -> None: ...
    def append_evidence(self, key: str, evidence: dict, body: dict) -> None: ...
    def save_result(self, key: str, result: dict) -> None: ...
    def mark_terminal(self, key: str, state: str) -> None: ...
